### ISSUE TITLE
T undefined

### ISSUE THREAD

**Issue by zenna** [FluxML/Tracker.jl#13]
T is not defined
```
Base.convert(::Type{<:TrackedArray}, x::TrackedArray) =
  error("Not implemented: convert $(typeof(x)) to $T")
```

https://github.com/FluxML/Tracker.jl/blob/4b64e81d56f6700964534bbaf4e5a252ff7260e8/src/lib/array.jl#L38

**Comment by MikeInnes** [comment]
It should be `convert(T::Type{<:TrackedArray}, ...)`. A quick PR would be great, from anyone who's interested.

**Comment by ChrisRackauckas** [comment]
The PR already existed to Flux too, so it's a pretty easy one.
