### ISSUE TITLE
Add `once=true` argument to the `gradient` function?

### ISSUE THREAD

**Issue by findmyway** [FluxML/Tracker.jl#32]
In some cases, I need to pass the `once=false` keyword argument to `back!` through the `gradient` function. So maybe add this extra argument to `gradient`?

**Comment by MikeInnes** [comment]
Why would you need this? If you call `gradient` then by definition you only call the pullback once.

**Comment by findmyway** [comment]
Let me explain why I need `once=true`.

A minimal network would be:

```
x -> w -> w1 -> loss_1
     | -> w2 -> loss_2 
```

In this case, I would like to first calculate gradient based on `loss_1` then `loss_2`. I can't sum `loss_1` and `loss_2` and `back!` only once, because they may have different optimizer. Then I get the error

```
`back!` was already used
```

So I think it is reasonable to add `once=true` to `gradient`. Then I can set `once=false` for `loss_1` and `once=true`  for  `loss_2`.

A MWE is:

```julia
x = rand(3,10)
y1 = rand(0:1, 10)
y2 = rand(0:1, 10)

mid = w * x

y1_est = w1 * mid
loss_1 = Flux.mse(y1_est, y1)
y2_est = w2 * mid
loss_2 = Flux.mse(y2_est, y2)

g1 = Tracker.gradient(() -> loss_1, Flux.params(w, w1))
g2 = Tracker.gradient(() -> loss_2, Flux.params(w, w2))
```
```
`back!` was already used

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] back_(::Tracker.Call{Missing,Tuple{}}, ::Array{Float64,2}, ::Bool) at /home/tj/.julia/packages/Tracker/AIiYy/src/back.jl:42
...
```

**Comment by MikeInnes** [comment]
You shouldn't do calculations you want to differentiate in global scope like that. Instead do

```julia
Tracker.gradient(params(...)) do
  mid = w * x
  ...
end
```

and this will work. Or alternatively you can define a function and do `gradient(() -> losses()[1], ps)` or something. In Zygote, the code you have now would return `nothing` gradients.

**Comment by findmyway** [comment]
Now I see.

Thanks for your explanation!
