### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mohamed82008** [FluxML/Tracker.jl#43]
Can we please get a new release? We need some of the latest ambiguity fixes over in Turing.jl.

**Comment by DilumAluthge** [comment]
Bump

**Comment by mohamed82008** [comment]
Bump

**Comment by MikeInnes** [comment]
Ref https://github.com/JuliaRegistries/General/pull/2780

**Comment by ChrisRackauckas** [comment]
@juliaregisrator register

**Comment by ToucheSir** [comment]
Did you mean to tag a release @ChrisRackauckas ?

**Comment by ChrisRackauckas** [comment]
Yeah sorry typo, as trying to do it on the bit of internet I could catch on the plane.

@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
