### ISSUE TITLE
Printf not defined

### ISSUE THREAD

**Issue by ChrisRackauckas** [FluxML/Tracker.jl#69]
https://travis-ci.org/github/SciML/DiffEqSensitivity.jl/jobs/700087790#L699-L713

Generally I think this needs some quick fixes and Julia v1.3 or higher testing.

**Comment by devmotion** [comment]
The test used Tracker 0.2.3 which is a quite old version (see https://github.com/FluxML/Tracker.jl/compare/v0.2.3...master). The issue was fixed by https://github.com/FluxML/Tracker.jl/pull/50, I assume.
