### ISSUE TITLE
Bug in Tracker 0.2.9?

### ISSUE THREAD

**Issue by devmotion** [FluxML/Tracker.jl#76]
Tracker 0.2.9 breaks DistributionsAD (see https://github.com/TuringLang/DistributionsAD.jl/issues/107) and apparently in OrdinaryDiffEq downstream tests it silently leads to incorrect values as well: https://github.com/TuringLang/Bijectors.jl/pull/126#issuecomment-672309267

Any idea what could have caused these bugs and how to fix them? Could they be caused by https://github.com/FluxML/Tracker.jl/pull/72?

**Comment by ChrisRackauckas** [comment]
Or possibly https://github.com/FluxML/Tracker.jl/pull/75 . A git bisect is probably in order.

**Comment by devmotion** [comment]
According to git bisect (I've never used it before, so maybe I messed up something...) https://github.com/FluxML/Tracker.jl/commit/555a632246b0b88e10c702c02e8666d487370423 is the first bad commit (i.e., the initial commit of https://github.com/FluxML/Tracker.jl/pull/72). I checked with the DistributionsAD tests.

**Comment by DhairyaLGandhi** [comment]
Could you try running tests against https://github.com/FluxML/Tracker.jl/pull/77

**Comment by devmotion** [comment]
Tests pass with https://github.com/FluxML/Tracker.jl/pull/77

**Comment by devmotion** [comment]
Fixed by Tracker 0.2.10.
